@startuml
start

:A. Setup;
:a1. Read number of students;
:a2. Initialize shared variables;
:a3. Initialize mutex and semaphores;
:a4. Allocate arrays for threads, ids, semaphores;

:B. Create threads;
:b1. Create 1 TA thread;
:b2. Create n student threads;
:b3. Give each student a unique id;

fork
  repeat
    :TA thread;
    if (c7. No student waiting\nand no current student?) then (yes)
      :TA sleeps;
    endif
    :d2. Wait for students_waiting;
    :Choose current student\nor next waiting student;
    :d3. Signal student_called[i];
    :c6. Help one student;
    :d4. Signal student_done[i];
  repeat while (running)

fork again
  repeat
    :Student thread;
    :c1. Program for random time;
    :c2. Ask TA for help;

    if (TA free and\nno one waiting?) then (yes)
      :c5. Wake TA if sleeping;
      :Get immediate help;
    else (no)
      if (c3. Chair available?) then (yes)
        :Wait in chair;
      else (no)
        :c4. Come back later;
      endif
    endif
  repeat while (running)

end fork

stop
@enduml